service: vue-3-vite-ssr

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs14.x
  profile: engaged
  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

functions:
  vue:
    handler: server.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

package:
  exclude:
    - src/**
    - tsconfig.json
  excludeDevDependencies: true
